export class CashService {
    // 설명서
    checkValue = () => {
        console.log("현금이 있는지 검증합니다.")
        // 1.가진돈을 검증하는 코드 (대략 10줄)
        // ...
        // ...
        // ... 
        // ...
        // ...
    }

}