version: "3.7"

services:
    my-backend:
        build: 
          context: .
          dockerfile: Dockerfile
        volumes:
          - ./index.js:/myfolder/index.js
          - ./user.js:/myfolder/user.js
          - ./models/coffeList.js:/myfolder/models/coffeList.js
          - ./personal.js:/myfolder/personal.js
        ports:
          - 3000:3000

    my-database:
        image: mongo:latest
        ports:
          - 27017:27017